contrat_index:
    path:     /
    defaults: { _controller: "JardinBundle:contrat:index" }
    methods:  GET

contrat_show:
    path:     /{id}/show
    defaults: { _controller: "JardinBundle:contrat:show" }
    methods:  GET

contrat_new:
    path:     /new
    defaults: { _controller: "JardinBundle:contrat:new" }
    methods:  [GET, POST]

contrat_edit:
    path:     /{id}/edit
    defaults: { _controller: "JardinBundle:contrat:edit" }
    methods:  [GET, POST]

contrat_delete:
    path:     /{id}/delete
    defaults: { _controller: "JardinBundle:contrat:delete" }
    methods:  DELETE
