<?php

namespace JardinBundle\Repository;

/**
 * InscriptionEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
